## File generated by the BNF Converter (bnfc 2.9.4).

# Makefile for building the parser and test program.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : Latte/Test compiler

compiler: Latte/Test src/*.hs lib/runtime.bc
	ghc -isrc src/main.hs -o compiler

semantics: Latte/Test src/*.hs
	ghc -isrc -prof -fprof-auto -fprof-cafs src/semantics-only.hs -o semantics

debug: Latte/*.hs src/*.hs
	ghc -isrc -prof -fprof-auto -fprof-cafs src/main.hs -o compiler

# Rules for building the parser.

Latte/Abs.hs Latte/Lex.x Latte/Par.y Latte/Print.hs Latte/Test.hs : Latte.cf
	bnfc --functor --haskell -d Latte.cf

# Create runtime.s file from runtime.c
lib/runtime.bc: lib/runtime.c
	clang -o ./lib/runtime.ll -Xclang -no-opaque-pointers -emit-llvm -S ./lib/runtime.c
	llvm-as -o ./lib/runtime.bc ./lib/runtime.ll

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

Latte/Test : Latte/Abs.hs Latte/Lex.hs Latte/Par.hs Latte/Print.hs Latte/Test.hs
	${GHC} ${GHC_OPTS} $@

# Rules for cleaning generated files.

clean :
	-rm -f Latte/*.hi Latte/*.o Latte/*.log Latte/*.aux Latte/*.dvi
	-rm -f src/*.o src/*.hi
	-rm -f lib/*.bc lib/*.ll

# EOF
