## File generated by the BNF Converter (bnfc 2.9.4).

# Makefile for building the parser and test program.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : Latte/Test

# Rules for building the parser.

Latte/Abs.hs Latte/Lex.x Latte/Par.y Latte/Print.hs Latte/Test.hs : Latte.cf
	bnfc --haskell -d Latte.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

Latte/Test : Latte/Abs.hs Latte/Lex.hs Latte/Par.hs Latte/Print.hs Latte/Test.hs
	${GHC} ${GHC_OPTS} $@

# Rules for cleaning generated files.

clean :
	-rm -f Latte/*.hi Latte/*.o Latte/*.log Latte/*.aux Latte/*.dvi

distclean : clean
	-rm -f Latte/Abs.hs Latte/Abs.hs.bak Latte/ComposOp.hs Latte/ComposOp.hs.bak Latte/Doc.txt Latte/Doc.txt.bak Latte/ErrM.hs Latte/ErrM.hs.bak Latte/Layout.hs Latte/Layout.hs.bak Latte/Lex.x Latte/Lex.x.bak Latte/Par.y Latte/Par.y.bak Latte/Print.hs Latte/Print.hs.bak Latte/Skel.hs Latte/Skel.hs.bak Latte/Test.hs Latte/Test.hs.bak Latte/XML.hs Latte/XML.hs.bak Latte/AST.agda Latte/AST.agda.bak Latte/Parser.agda Latte/Parser.agda.bak Latte/IOLib.agda Latte/IOLib.agda.bak Latte/Main.agda Latte/Main.agda.bak Latte/Latte.dtd Latte/Latte.dtd.bak Latte/Test Latte/Lex.hs Latte/Par.hs Latte/Par.info Latte/ParData.hs Makefile
	-rmdir -p Latte/

# EOF
